version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=mysql-db
    ports:
    - "3306:3306"
    networks:
      static-network:
        ipv4_address: 172.20.128.1
    volumes:
      - ~/volumes/mysql-data:/var/lib/mysql

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ~/volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      #- es-net
      static-network:
        ipv4_address: 172.20.128.2
    ports:
      - 9200:9200  
      
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.17.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      #- es-net
        static-network:
          ipv4_address: 172.20.128.3
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  static-network:
    ipam:
      config:
      - subnet: 172.20.0.0/16
        #docker-compose v3+ do not use ip_range
        ip_range: 172.28.5.0/24
volumes:
  mysql-data:
  elasticsearch-data: